# Generated by Django 5.2.2 on 2025-06-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="faces/")),
                ("encoding", models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
